name: Build

on:
  push:
    branches:
      - main
      - release-*
    tags:
      # YYYYMMDD
      - "20[0-9][0-9][0-1][0-9][0-3][0-9]*"
  pull_request:
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  build-amd:
    runs-on: ubuntu-latest
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build
        id: build
        with:
          platform: amd64
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build-arm:
    runs-on: ubuntu-24.04-8core-arm
    # Arm builds cost money, skip them on PRs.
    if: github.event_name != 'pull_request'
    outputs:
      digest: ${{ steps.build.outputs.digest }}
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - uses: ./.github/actions/build
        id: build
        with:
          platform: arm64
          github_token: ${{ secrets.GITHUB_TOKEN }}
  build-multi-platform-docker:
    if: github.event_name != 'pull_request'
    needs: [build-amd, build-arm]
    runs-on: ubuntu-latest
    steps:
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Github Container Repo
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner  }}
          password: ${{ secrets.GITHUB_TOKEN  }}

      - name: Docker meta
        id: meta
        uses: docker/metadata-action@v5
        with:
          images: ghcr.io/espressosystems/staking-ui-service
          flavor: latest=true

      - name: Create and push branch tag
        uses: Noelware/docker-manifest-action@master
        with:
            tags: ghcr.io/espressosystems/staking-ui-service:${{ steps.meta.outputs.version }}
            inputs: ghcr.io/espressosystems/staking-ui-service@${{ needs.build-amd.outputs.digest }},ghcr.io/espressosystems/staking-ui-service@${{needs.build-arm.outputs.digest}}
            push: ${{ github.event_name != 'pull_request' }}

      - name: Create and push latest tag
        uses: Noelware/docker-manifest-action@master
        with:
            tags: ghcr.io/espressosystems/staking-ui-service:latest
            inputs: ghcr.io/espressosystems/staking-ui-service@${{ needs.build-amd.outputs.digest }},ghcr.io/espressosystems/staking-ui-service@${{ needs.build-arm.outputs.digest }}
            push: ${{ github.event_name != 'pull_request' }}
